apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: iamtest
  name: iamtest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iamtest
  template:
    metadata:
      labels:
        app: iamtest
    spec:
      containers:
      - image: docker.io/wlsgh0122/iamtest
        name: iamtest
