apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: iamtest
  name: iamtest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iamtest
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: iamtest
    spec:
      containers:
      - image: docker.io/wlsgh0122/iamtest
        name: iamtest
        resources: {}
status: {}
